server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro-mp-boot?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&tinyInt1isBit=false&allowMultiQueries=true&useSSL=false&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name:  com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#  #集成Freemark
#  freemarker:
#    cache: false
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html;charset=utf-8
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request
#    allow-session-override: true
#    template-loader-path: classpath:/templates
#    suffix: ftl

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #驼峰式命名映射
    db-column-underline: true
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
  #model包
  type-aliases-package: com.qihang.shiro_test.entity
  mapper-locations: mapper/*.xml




